### ISSUE TITLE
Any female devs interested in presenting to highschoolers?

### ISSUE THREAD

**Issue by patrickgordon** [BrisRuby/meetups#100]
Peta from RCL sent this out to residents today. It could be a great learning experience for anyone interested in building their presentation / soft skills.

"I wondered if you knew someone who would be willing to speak to a small group of year 11 female students and explain about how they became a developer, what it is like to run your own business and to help support girls into IT.  I would be extremely grateful if you could recommend someone.

Essentially they will inform the projects that the students are getting involved in and assist them to create their first live websites.  

The dates I would need the person would be either

Thursday 7 May, 8.30 - 10.30

or

Monday 11 May, 8.30 - 10.30

We would pay $100 per hour. We are based at Kedron so not too far away.

Warm regards.
 
Linda Clark
 
Information Technology Teacher
Mount Alvernia College
82 Cremorne Road
Kedron
 
tel: 07 3357 6000
clarl@mta.qld.edu.au
@linda_clarky
"

**Comment by mattconnolly** [comment]
Right across the road from where I went to school!

I’d love to help out, except that now living in California makes it impossible to be there in person. Video conferencing over FaceTime or something might be an option, but the timezone difference would be a challenge. Happy to explore if that option is possible….

-Matt

**Comment by patrickgordon** [comment]
AFAIK This has been filled.
