### ISSUE TITLE
Using Inspectlet to solve UX issues

### ISSUE THREAD

**Issue by patrickgordon** [BrisRuby/meetups#101]
It's not really Ruby or Ruby on Rails specific but more about how using an analytics tool can help solve issues you otherwise wouldn't know about.

We're using this with our product and I'd be happy to give a demo of how it works and how we used it to solve a real production UX issue.

Will also cover how to install and set it up (very easy).

**Comment by patrickgordon** [comment]
I can't apply a label so it would be:
Beginner and Wanna Do It

**Comment by ghiculescu** [comment]
:+1:  We have Inspectlet installed but don't look at it very much, so would be keen to see some tips on better ways to use it.

**Comment by nicholasburge** [comment]
+1

**Comment by ridget** [comment]
+1

**Comment by patrickgordon** [comment]
Done last night.

Slides:
http://www.slideshare.net/PatrickGordon3/brisruby-inspectlet
