### ISSUE TITLE
Crash Course: EmberJS with Rails

### ISSUE THREAD

**Issue by patrickgordon** [BrisRuby/meetups#102]
I'd really love a crash course on using the popular JS framework Ember with Rails.

I don't want to do it (because I know nothing about it) but I know there's a few regulars who are really on top of this (*cough* Geoff *cough*).

Alternatively: AngularJS or React with Rails.

**Comment by nigelr** [comment]
@patrickgordon, @geoffreyd is doing an Ember talk at BrisJS next week..

**Comment by nigelr** [comment]
@geoffreyd was a great overview of what Ember was... Do you want to do a 20 minutes practical on connecting Rails and Ember this month as a follow on?

**Comment by michael-harrison** [comment]
+1 I'd really like to see how authentication works with something like devise

**Comment by nigelr** [comment]
@geoffreyd thanks for your talk last month
