### ISSUE TITLE
Refactoring in Ruby

### ISSUE THREAD

**Issue by jamesottaway** [BrisRuby/meetups#105]
@daphsta [shared a link in Slack](https://brisbane.slack.com/archives/ruby/p1438126980000076
) to some of her [favourite refactoring talks](https://infinum.co/the-capsized-eight/articles/best-ruby-on-rails-refactoring-talks).

I really like the idea of adapting one or more of these talks while we're focusing on beginner concepts.

I'm happy to present one or more, and I'm sure there are others who would be willing to pitch in.

**Comment by iconnor** [comment]
Happy to tag team and show how to measure your refactoring via #104 static analysis.

**Comment by ridget** [comment]
:+1 whilst I suspect I wont be in attendance for a while, happy to pitch in on this/would love to see it. Would some pattern intro talks be out of the question?

**Comment by gizotti** [comment]
:+1:

**Comment by nigelr** [comment]
@jamesottaway can we put this down for Septembers BrisRuby (need to give you a break from talking otherwise we will burn you out)... 
Ps. Awesome that you are back and doing talks again... Your talks are always well received.

**Comment by jamesottaway** [comment]
I'll be out of town for most of September, but you can lock me in for October.
