### ISSUE TITLE
#Timezones

### ISSUE THREAD

**Issue by langsharpe** [BrisRuby/meetups#106]
- What is time
- Useful representations of time
- What is a timezone
- How to handle timezones in your application

I'm putting my hand up to do this talk.

**Comment by ridget** [comment]
:+1: I dont think i know of anyone who hasnt had a timezone issue theyve had to resolve.

**Comment by iconnor** [comment]
Getting DST right and calculating business time can also be tricky

**Comment by patrickgordon** [comment]
:+1: had to deal with this when I first started. PITA for a noob.

**Comment by michael-harrison** [comment]
+1 I've dealt with this on a regular basis and it can be a trap for the uninitiated.  Rails does help out but doing it with just ruby can be a challenge :)

**Comment by nigelr** [comment]
@langsharpe awesome topic... I will put you down for the next BrisRuby on the 25th

**Comment by nigelr** [comment]
@langsharpe thanks for your talk last month
