### ISSUE TITLE
Non-software backgrounds

### ISSUE THREAD

**Issue by jamesottaway** [BrisRuby/meetups#108]
A recent blog post from Avdi Grimm details his experience with [conference talks which are only tangentially related to software development](http://devblog.avdi.org/2015/07/23/out-beyond-ruby-there-is-a-field-i-will-meet-you-there/).

I'm wondering whether any newcomers to BrisRuby have stories they wish to share regarding their backgrounds, and what led them to the Ruby community?

I spoke to a few of the RailsGirls attendees who have backgrounds in things like marketing and education, so I thought someone out there may be interested in sharing something a little different with us.

PS. Do yourself a favour and follow [Avdi's blog](http://devblog.avdi.org/)!

**Comment by AmyHilaire** [comment]
Hi James,

I'm a Rails Girls graduate from a non-software background. I'm an occupational therapist, I work with kids who have disabilities. Since Rails Girls, I've been building a occupational therapy blog using Middleman with Rails. I'm not sure my story would be as interesting as Alpacas, but I'd be happy to share my experiences.

Amy

**Comment by hackling** [comment]
+2 to Amy sharing her experiences.

As a Rails Girls mentor, I love hearing anything about the people who went through the course.

**Comment by davekinkead** [comment]
Are you happy to share your experience this month Amy?  Any other Rails Girls too?

**Comment by patrickgordon** [comment]
Would really like to hear this :+1:

**Comment by AmyHilaire** [comment]
I'm sure I can put something together :-)
Would be glad for other Rails Girls to join me, or share your stories next
time...

Amy

**Comment by davekinkead** [comment]
Great talk @AmyHilaire. If you want to write a quick blog post about it, we could put that up on http://brisruby.org/talks/

Just a Jekyll/Minute man file is all that's needed :)
