### ISSUE TITLE
Photogenic Ruby

### ISSUE THREAD

**Issue by elliotthilaire** [BrisRuby/meetups#109]
I've been playing around with controlling my camera programmatically (and trying to use Ruby when doing do).

I've had mixed levels of success using various methods (USB, Infrared, Cable release) and devices (MacBook, Arduino, Raspberry Pi).

I could do a break down of the different ways to interface with a camera and the challenges I've come across when trying to achieve this using Ruby.

This would be a whirlwind tour with some electronics, a few photos, some gems, and a little bit of Ruby.

Maybe a 15-20 minute talk.

**Comment by davekinkead** [comment]
Cool talk! Ta.
