### ISSUE TITLE
Contentful (Admin Interface as a Service)

### ISSUE THREAD

**Issue by elliotthilaire** [BrisRuby/meetups#112]
Feel like your repeating yourself re-implementing all the forms for an admin interface?

Contentful https://www.contentful.com/  is an 'API-first CMS'  They take care of the interface for admin/ content-creators and expose an API for you to consume and display the content/data in your app however you want.

I think this approach has a lot of merits. I'm keen to show it off if people are interested.

**Comment by nigelr** [comment]
thanks for the talk @elliotthilaire
