### ISSUE TITLE
Use Rails to fix bugs in our democracy

### ISSUE THREAD

**Issue by equivalentideas** [BrisRuby/meetups#113]
Hi there 👋 

Luke from the [OpenAustralia Foundation](https://www.openaustraliafoundation.org.au/) here. I'm going to be up in [Brisbane for the Hacks/Hackers meetup](http://www.meetup.com/Hacks-Hackers-Brisbane/) on May 25th.

I'd love to come meet the Brisbane crew and tell you a bit about our some of our Ruby and Rails projects like [They Vote For You](https://theyvoteforyou.org.au) , [morph.io](https://morph.io) , [Right To Know](https://www.righttoknow.org.au/) and [PlanningAlerts](https://www.planningalerts.org.au). I'm a big fan of Roro Sydney ❤️  and we've given talks about different our projects and how people can get involved there a number of times. All our projects are open source and dozens of people contribute Ruby code to them to make our democracy work better.

Would you be interested in me giving a short presentation at the May 24th Meetup on how we're using Ruby to fix bugs in our democracy and how people can do it too?

**Comment by patrickgordon** [comment]
Sounds interesting.
Thoughts @nigelr ?

**Comment by davekinkead** [comment]
🏁
