### ISSUE TITLE
What would your team do round 2

### ISSUE THREAD

**Issue by ridget** [BrisRuby/meetups#114]
Plus one in here for any issue you'd like to discuss. We'll probably constrain it to one or two topics this time around, I've listed a suggestion thats already been supplied:

- [ ] git workflows
- [ ] Strategies for choosing a gem.

**Comment by patrickgordon** [comment]
I've always wondered about gem selection in teams. Since I only work solo I just use gems whenever I think it'll save me time and solves the problem. But I suspect there's more to it then that when working on a production product in a team

**Comment by michael-harrison** [comment]
+1
