### ISSUE TITLE
Oauth 2

### ISSUE THREAD

**Issue by patassetbuilders** [BrisRuby/meetups#115]
Love to understand more about OAuth 2

**Comment by ridget** [comment]
bump :) anyone else interested in hearing more about this?

**Comment by ghiculescu** [comment]
I can do this talk if you like.

**Comment by ridget** [comment]
@patassetbuilders / @ghiculescu closing this one off as we've had no further discussion on it. Please open a new issue if you'd like to do or see this talk :)
