### ISSUE TITLE
What would you like to know more about?

### ISSUE THREAD

**Issue by danieldraper** [BrisRuby/meetups#116]
I have a side project built in Ruby on Rails, its now over 2 years old. Would anyone be interested in hearing about the project and if so what specifically? You can checkout the site at www.memberhub.com.au.

Otherwise what topics are people interested in hearing about this year?

PS. If you try and sign-up its not an automated process and I will be emailing or phoning you.

**Comment by ridget** [comment]
@danieldraper i'm pretty interested in hearing about how you've taken the initial project and dealt with legacy decisions and code as you've brought on users and how you've been managing that. What decisions have you made early on that's made bringing on new users and features easier/harder now?

**Comment by ridget** [comment]
@danieldraper closing this as we've had no further discussion on this one.
