### ISSUE TITLE
What is your best MVC analogy for teaching beginners?

### ISSUE THREAD

**Issue by nathanhoad** [BrisRuby/meetups#118]

**Comment by lillypiri** [comment]
Here's mine: 

<img src="https://s3.amazonaws.com/lillypiri/blog/MVC/big_mvc_barista2.gif">

**Comment by ridget** [comment]
@lillypiri thanks so much for your input and amazing talk this year. I'm going to close this issue off as part of tidying up the issues for the new year. cc @nathanhoad
