### ISSUE TITLE
Programming, Power, & Politics

### ISSUE THREAD

**Issue by davekinkead** [BrisRuby/meetups#124]
Politics is about power.  It is the ability to influence social action - to charm, to leverage, to coerce. Whenever you alter power structures, you are engaging in politics.  

Software is eating the world.  Startups innovate and they hustle.  They disrupt.  Google, Github, Uber - these are dramatic examples of how software alters existing power structures creating both winners and losers.

So it follows then, that writing software is a political act.  Every feature you push is what Foucault called a structural expression of a complex strategic situation in a given social setting.  Every feature you push alters existing power structures.  Every feature you push alters the balance winners and losers.

Software is changing the world.  What type of world it becomes will be determined by you.

**Comment by ridget** [comment]
@davekinkead are you ok to give this talk this month?

**Comment by davekinkead** [comment]
It's on like donkey kong @ridget!

**Comment by ridget** [comment]
@davekinkead can you flick me a link to your slidedeck?

**Comment by davekinkead** [comment]
Sorry for the delay — new MacBook so I need to transfer it from my old one.
