### ISSUE TITLE
Intro to rails i18n

### ISSUE THREAD

**Issue by ghiculescu** [BrisRuby/meetups#125]
I wrote a blog post on the topic https://medium.com/tanda-developers/things-we-learned-translating-our-saas-product-24399b1aef48

But if anyone's interested, happy to do a talk too!

**Comment by ridget** [comment]
@ghiculescu this was an entertaining post, thanks for the write up, would love a talk. Would next month be ok ?

**Comment by ghiculescu** [comment]
@ridget what would the date be? just gotta check if i'll be in town.

**Comment by ridget** [comment]
@ghiculescu Tuesday July 25th @ 6:30pm

**Comment by ghiculescu** [comment]
i'll be out of the country :( can i do the one after?

**Comment by ridget** [comment]
@ghiculescu works for me :) thanks for volunteering

**Comment by ridget** [comment]
@ghiculescu still interested in giving this talk in August?

**Comment by ridget** [comment]
@ghiculescu is this a talk you're still interested in giving?

**Comment by ridget** [comment]
@ghiculescu closing this issue, if you'd like to resubmit the talk, please open a new issue.
