### ISSUE TITLE
Object serialisation with Oj

### ISSUE THREAD

**Issue by DougFlemingAED** [BrisRuby/meetups#126]
Hey Tom, if you're still looking for topics, I'm happy to talk briefly about a Gem called OJ for object serialisation.

**Comment by ridget** [comment]
DougFlemingAED this would be great thanks chief. We've got a lightning talk night this month,  could I book you in for next month?

Alternatively if its a lightning talk more than welcome to give it this month :)

**Comment by DougFlemingAED** [comment]
I can do a lightning talk about it, the main usefulness of the Gem can be summed up in just a few minutes with a quick example using pry or something.

Do your lightning talks usually involve quick demos?

**Comment by ridget** [comment]
@DougFlemingAED thanks for presenting your lightning talk mate, do you have a copy of your slides?

**Comment by DougFlemingAED** [comment]
Hey Tom, sorry no slides for that one, Nigel asked me on the night if I wanted to talk about anything, and based on what we had discussed, I put my hand up for the OJ gem, but it was all just demo on the screen via terminal.

**Comment by ridget** [comment]
@DougFlemingAED thanks for the amazingly fast reply, especially given the time since giving the talk. Going to close this one off then :)
