### ISSUE TITLE
Crystal Lang - fast as C, slick as Ruby

### ISSUE THREAD

**Issue by kimburgess** [BrisRuby/meetups#127]
Heavily inspired by Ruby's syntax, Crystal is a statically typed, compiled language that emits native code via LLVM.

**tl;dr** it's ballin'

They're aiming for a 1.0.0 release by the end of this year. I'm still super new to it, but definitely watching it closely. I'd love to do a short talk and introduce others to why it's interesting and where development is at.

More info: https://crystal-lang.org/

**Comment by ridget** [comment]
@KimBurgess would love to hear this, how long is a short talk though? I've tentatively got 2 speakers lined up for the next meetup, so if its a lightning I can fit you in, otherwise are you ok to speak next month?

**Comment by kimburgess** [comment]
Happy to do either. What about a lighting talk as a quick intro, then can dive in deeper at some point in the future if there's general interest.

**Comment by ridget** [comment]
@KimBurgess that sounds great. Thank you for volunteering :) Can you let me know a quick working title, would like to advertise the next meetup on Monday

**Comment by kimburgess** [comment]
No problems. Let's go with the one above.

**Comment by jamiecook** [comment]
I'd be keen to hear more about Crystal - it sounds like a pretty good
tradeoff between ruby/C

*Jamie Cook*
Software Team Leader

*Veitch Lister Consulting*
Level 5, 200 Mary Street, Brisbane QLD 4000
PO Box 15080, City East, QLD 4002
*T* +61 7 3870 4888 <+61%207%203870%204888> *M* +61 418 772 610
<+61418772610> *W* www.veitchlister.com.au

<http://www.veitchlister.com.au/>
<https://www.linkedin.com/company/veitch-lister-consulting>

**Comment by ridget** [comment]
@KimBurgess I'm closing this issue, thanks for your original talk. Can you open a new issue if you'd like to do that deeper dive in future?
