### ISSUE TITLE
Introduction to Background processing 

### ISSUE THREAD

**Issue by angusscown** [BrisRuby/meetups#128]
It's not always clear to web developers when you should use background work rather than doing things inside a web request.   

This talk gives an overview of why we take things out of the web request and then will go into some sidekiq specific implementations.  

I've been using Sidekiq and before that delayed job and before that.....

**Comment by ridget** [comment]
@angusscown Would you be keen to present this next month in October?

**Comment by angusscown** [comment]
I've got a bit of travel in October. What date?

**Comment by ridget** [comment]
@angusscown Tues Oct 24.

**Comment by ridget** [comment]
@angusscown can we confirm you at this point?

**Comment by angusscown** [comment]
Tom, sorry mate.  I've been called to Melbourne next week.   If that
changes later in this week I'll let you know.

**Comment by ridget** [comment]
@angusscown no worries :), I've got another speaker lined up, just wanted to give you first right of reply. Can we tentatively lock you in for November?

**Comment by ridget** [comment]
@angusscown is this still a talk you'd like to give in the new year? Otherwise will close this issue off.
