### ISSUE TITLE
The Campsite Rule - Leaving the Tech Industry Better than We Found It 

### ISSUE THREAD

**Issue by web-goddess** [BrisRuby/meetups#130]
I'm trying to plan a quick trip to Brisbane later this month and realised I'll be there for the October meetup. I could do a cut-down version of the keynote I gave at DDD Perth...

**The Campsite Rule - Leaving the Tech Industry Better than We Found It** 
Improving the codebase for the next developer is a great goal, but what about making the industry better for the next generation? We all know there are days when we're tempted to ragequit, but there is an antidote - becoming a mentor! You’ll learn how you can change your own behaviour and thinking, be more supportive to those just starting out, and feel more engaged and inspired in your work - all with minimal effort. We all have a responsibility to make things just a little bit better for those who come after us.

Any interest?

**Comment by ridget** [comment]
@web-goddess That would be fantastic, thank you! Meetup kicks off at 6:30, how long a slot would you like?

**Comment by web-goddess** [comment]
Hey Tom! I'm going to attempt a 20 min version at Girl Geek Sydney next week, but call it 25 to be safe. :)

**Comment by ridget** [comment]
@web-goddess perfect, thank you :)

**Comment by ridget** [comment]
@web-goddess just in case, our projector works on a 4:3 ratio

**Comment by web-goddess** [comment]
Thanks for letting me know! I'll see you then. I think you've got my email courtesy of Nigel, and my mobile number is in the signature if you need to reach me on the day...

**Comment by ridget** [comment]
@web-goddess thanks again for your amazing talk, can we please get a link to the slidedeck if possible?

**Comment by web-goddess** [comment]
@ridget Hey Tom - sorry I missed this until now! Here you go: [https://www.slideshare.net/KristineHoward1/the-campsite-rule-leaving-the-tech-industry-better-than-we-found-it](https://www.slideshare.net/KristineHoward1/the-campsite-rule-leaving-the-tech-industry-better-than-we-found-it)

**Comment by ridget** [comment]
@web-goddess thanks so much!
