### ISSUE TITLE
Sneak peek at Telstra's new The Programmable Network 

### ISSUE THREAD

**Issue by developersteve** [BrisRuby/meetups#131]
Happy to do a bit of a demo if there's interest

**Comment by ridget** [comment]
@developersteve sounds great. You free to talk this coming Tuesday?

**Comment by developersteve** [comment]
@ridget yup saw the call out for lightning talks and thought it might be a good op to show it off a bit (its freaking cool).

**Comment by ridget** [comment]
@developersteve thanks! Just about to send the mailout too :)

**Comment by ridget** [comment]
@developersteve Thanks so much for your talk last night! Could we get a link to the slide deck please?
