### ISSUE TITLE
Presenters

### ISSUE THREAD

**Issue by addstar34** [BrisRuby/meetups#133]
A talk about what are presenters, why you should use presenters and how to implement a presenter.

**Comment by ridget** [comment]
@addstar34 can we get a link to your slides please mate?

**Comment by addstar34** [comment]
@ridget this is funny because... here's my slides haha, I went the live coding route for my talk and took the minimalist approach for my slides.

![pasted image at 2017_11_27 12_14 pm](https://user-images.githubusercontent.com/13564150/33742912-46da6806-dbf6-11e7-8442-d6ffc0e1b71b.png)

**Comment by ridget** [comment]
@addstar34 im sorry mate, i completely forgot about that. Closing issue :)
