### ISSUE TITLE
Soft Skill : Fixed Mindset Vs Growth Mindset

### ISSUE THREAD

**Issue by jawdinmorris** [BrisRuby/meetups#139]
Hi,
I'm a new developer, currently studying at Coder Academy. I did a talk a couple months ago for Brisbane Tech Newbies regarding the issues of a fixed mindset, the benefits of a growth mindset and some methods for teaching yourself how not to feel like a developer 'impostor'. 

Let me know if you'd be interested in giving this talk or if it's not the right fit.

A copy of the slides can be found: https://www.canva.com/design/DACxwT7Klis/cDL-PhdErNuoeSz1gSNAOg/edit

**Comment by ridget** [comment]
@jawdinmorris This sounds great! Can we confirm you for the meetup on the 22nd of May?

**Comment by michael-harrison** [comment]
+1

**Comment by jawdinmorris** [comment]
@ridget That sounds great! It takes about 15 minutes so far so would be perfect for just a lightening talk.

**Comment by jawdinmorris** [comment]
Hi, just confirming if you wanted me to present tomorrow night?

**Comment by ridget** [comment]
@jawdinmorris apologies for not following up, yes please!

**Comment by jawdinmorris** [comment]
No worries @ridget, see you tomorrow night :)
