### ISSUE TITLE
Proposal? Service object talk (again?)

### ISSUE THREAD

**Issue by ecoologic** [BrisRuby/meetups#146]
I'm giving a quick talk (~20m) in my company about services, so I have it ready and I can present it to the meetup too.

It goes:

1) A touch of restful
2) MVC frameworks
3) Why fat models don't work in big apps (circular dependency)
4) How to solve circular dependency
5) Service is a strange name (why not Go4 Operation)
6) Naming, folder structure
7) A real world example

I'm sure many of us are tired of hearing this, but, as I said, I have it ready...

**Comment by papz** [comment]
I'd like to see this just to let you know, but I'll prob miss it as I won't be there until April.

**Comment by nigelr** [comment]
@ecoologic any chance you can do this on Tuesday?

**Comment by ecoologic** [comment]
@nigelr - Sure.  Is there a whiteboard at the library? (I don't have slides, I'd like to be able to sketch a few concepts)
