### ISSUE TITLE
Intercom.io

### ISSUE THREAD

**Issue by ghiculescu** [BrisRuby/meetups#55]
We've found [Intercom](https://www.intercom.io/) to be a huge win in being more in touch with new and existing customers. Would be happy to give a talk about it if others are interested.

**Comment by davekinkead** [comment]
@ghiculescu would be great to hear a talk on effective comms with customers this month.  Are you up for 27 Jan?

**Comment by ghiculescu** [comment]
In Japan until the 2nd :(

Next one, promise!

Alex Ghiculescu
alex@tanda.co

**Comment by davekinkead** [comment]
Done!

**Comment by RachelleOnRails** [comment]
:+1:

**Comment by Loordo** [comment]
:+1:

**Comment by davekinkead** [comment]
Hope your back from the japow-pow @ghiculescu as you are booked in for this month.  Let me know if it's good to go

**Comment by ghiculescu** [comment]
I am (a bit regretfully) back! When's the meetup?

**Comment by davekinkead** [comment]
http://www.meetup.com/BrisRuby/events/219376007/

**Comment by ghiculescu** [comment]
Yep, lock me in.

**Comment by markgandolfo** [comment]
Out of interest, what is TheLocker? googling and I'm coming up with Lacrosse social networks

**Comment by darrenrogan** [comment]
That is theLocker, it is an American startup that is focusing on Lacrosse to start.
