### ISSUE TITLE
Load testing using selenium and typhoeus - over 2 meetups

### ISSUE THREAD

**Issue by zubinix** [BrisRuby/meetups#75]
Will present over 2 consecutive meetups.

1. Lightening talk - Overview of the typhoeus HTTP client library.
2. Longer talk - Using selenium and typhoeus for load testing, maybe with an AWS (Amazon cloud) demo.

**Comment by nigelr** [comment]
@zubinix when can you do this talk?

**Comment by zubinix** [comment]
@nigelr November is do-able for me.

**Comment by zubinix** [comment]
@nigelr Also I don't mind doing a lighting talk on the Typhoeus gem this month if you want.
