### ISSUE TITLE
Ecommerce app using Spree, customise to existing website with Bootstrap

### ISSUE THREAD

**Issue by markwiggles** [BrisRuby/meetups#76]
Thinking about follow on from last brief talk at quiet meetup... 

Show demo to get Ecomm site up and running in 5 mins.
Briefly discuss:
- Routing inside Spree
- Admin options - add/remove products, gateways etc
- Use Deface library to replace/extend views.
- Access Spree Controller helpers

...so about 10-15 mins.  Really don't get it with these labels - anyway - <strong> BEGINNER & WILL DO </strong>

**Comment by markgandolfo** [comment]
+1
If you can add subscriptions to that talk I'll be even happier.

**Comment by davekinkead** [comment]
@markwiggles did you want to present this talk on 27 Jan?

**Comment by jaymiejones86** [comment]
+1

**Comment by markwiggles** [comment]
sure,  that will be ok  I can do for next Tuesday



Mark Wigglesworth ?
________________________________

**Comment by davekinkead** [comment]
Excellent!

**Comment by patassetbuilders** [comment]
Hi Mark

the web address is http://www.gotealeaf.com/
ps thanks for the talk last night.

Pat

**Comment by markwiggles** [comment]
thanks Pat


I am checking it out webpage now..


- like the way they say "this is the last stop..."


Seems like a very well constructed program!


cheers

Mark


Mark Wigglesworth ?
________________________________
