### ISSUE TITLE
Tools for remote pairing and where to find them

### ISSUE THREAD

**Issue by ridget** [BrisRuby/meetups#82]
So as part of my 52pairs project, half the battle has been in finding a tool for remote pairing that deals well with horrible upload speeds. This is a quick little talk about some of the services and technologies out there to make remote pairing a little easier.

**Comment by hackling** [comment]
I've used SSH + TMUX + Vim + Google Hangouts (to talk) once or twice before. Not sure I'm qualified enough to talk about it though :D

**Comment by ridget** [comment]
@hackling I've also had experience recently with screenhero and floobits, did you want to pair up on this one?

**Comment by NicholasTD07** [comment]
How does it work for two Vim users with different .vimrcs while pairing by using tmux and ssh?

And if you are using SSH and don't have an ideal type-response time(the time between you type a character and it actually being shown), I recommend having a look at [Mosh](https://mosh.mit.edu) and try it out.

**Comment by ridget** [comment]
@NicholasTD07 afaik if you pair with someone on their tmux session, you're using their tmux and vim bindings

The SSH response time I'm getting is cool, its mainly upload speed issues with video/talk screensharing and remote desktop through screenhero which is the issue atm. So much so that I'm now investing time into tmux/tmate and floobits.

**Comment by NicholasTD07** [comment]
@ridget It must feel weird to be in someone else's Vim for someone like me who has a nearly 300 lines .vimrc file.

Floodbits looks promising to me. :laughing:

Love to learn more. Looking forward to your talk.

**Comment by michael-harrison** [comment]
I've been pairing with reasonable success using a [TeamViewer](http://www.teamviewer.com/en/index.aspx) and Skype combo with all my team being remote.  TeamViewer tends to perform fairly well even at low bandwidth with one of my regular pairing session partners having **ADSL1**.  This allows us to transmit a high resolution screen (1920 x 1200) + audio.

**Comment by ridget** [comment]
@davekinkead @nigelr any opinions on having a bit of a round table on this?

**Comment by jasoncodes** [comment]
I’ve used tmux+vim over SSH many times with great success.

TeamViewer running in a VM for a shared web browser works pretty well. I tried ScreenHero but it dropped out all the time.

For audio, I’ve been using FaceTime Audio lately (on iPhone with headphones) with great success. Skype works okay but seems to burn a lot of CPU time.

**Comment by davekinkead** [comment]
A round table seems like a good idea. Maybe few different people with a 5min pitch each for their preference, what they like & don't like etc.

If anyone is keen for this, pls comment with your name and preferred pairing tool.  2-4 people would be ideal

**Comment by ridget** [comment]
@davekinkead ill put my hand up for floobits

**Comment by davekinkead** [comment]
@jasoncodes @michael-harrison @hackling @NicholasTD07 are any of you keen to take part? It would be good at least to have someone pimping tmux+vim, mosh .... skype even?

**Comment by NicholasTD07** [comment]
@davekinkead I haven't done any remote pair programming. And I am with @ridget, I think Floorbits looks promising.

**Comment by michael-harrison** [comment]
Just working out if I can make it to the meeting next week.  After doing a lot of years of remote programming I see a lot of solutions falling down on either they don't deal well with low bandwidth or if they do they lack the visual options when pairing on UI work.  Happy to share my experiences if I can make it.

**Comment by hackling** [comment]
With regards to Vim and different keybindings,

A while back @jasoncodes and I (mostly @jasoncodes) worked on [Vim Locksmith](https://github.com/jasoncodes/dotfiles/blob/master/bin/vim-locksmith).

You'd have to be using [fresh](http://freshshell.com/) (which I hope you are if your `.vimrc` is that long), but basically, you can extract all the key mappings from someone else's .vimrc and apply them to your .vimrc.
