### ISSUE TITLE
Getting started with lotus.rb

### ISSUE THREAD

**Issue by ridget** [BrisRuby/meetups#86]
We've all felt the friction of Rails when trying to apply OOD principles, that's why I'm kinda excited by [lotus](http://lotusrb.org/) which promises better adherance to SRP and more flexibility. Of course, I have no idea about it, so a talk seems like the best way to get up to speed.

**Comment by michael-harrison** [comment]
Seems like there's a couple of new ruby frameworks evolving. Have you had a look at [volt](http://voltframework.com) which also has [Ruby Rogues Podcast](http://devchat.tv/ruby-rogues/193-rr-the-volt-framework-with-ryan-stout) ? Like Lotus it's in the early stages but worth a look in 😎

**Comment by Loordo** [comment]
Volt looks awesome.

**Comment by ridget** [comment]
@michael-harrison @Loordo either of you interested in doing a head to head on it? Maybe throw another framework in the mix?

**Comment by Loordo** [comment]
I'm a bit to green. Someone with a bit more exp would be ideal!

**Comment by michael-harrison** [comment]
@ridget I'll have to have a play with volt but it sounds like a good idea.  Each framework has a different approach, for example Volt is focused on simplifying application creation using isometric development (i.e. ruby on the server & the browser) where as Lotus is clearly focused on the server with a very clean DSL.  Maybe that's one of the focuses for the talk; the choices in approach we are soon to have for application development.  There are other ways to develop an applications using ruby other the rails way :)

**Comment by ridget** [comment]
@michael-harrison you and I both. Haven't played with lotus yet. I think the different approaches to development could make for an interesting discussion.
