### ISSUE TITLE
Make me a faviocon. Pretty please.

### ISSUE THREAD

**Issue by davekinkead** [BrisRuby/meetups#88]
Any designer types able to turn our funky ruby logo into a favicon? http://brisruby.org/

I will love you long time if you do. Pinky promise.

**Comment by NicholasTD07** [comment]
Any specific requirement? Or just making it smaller?

**Comment by davekinkead** [comment]
Nope just a small version of the icon we have.  Unless you can make it do something cool like vomit rainbows....

**Comment by darren-james** [comment]
Have you tried just using a site like:
http://www.favicomatic.com/ <http://www.favicomatic.com/> 

____________________________
Darren James
darren@corepoint.com.au
0423 915 225

CONFIDENTIALITY NOTICE:

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited without written permission.

**Comment by nil0bject** [comment]
not sure if this is correct. just trying it out, so you have something and i have kinkea long time love
rename to favicon.ico

![favicon](https://cloud.githubusercontent.com/assets/953302/6365989/f4debcda-bd0a-11e4-89a1-96e9b6867588.png)

**Comment by davekinkead** [comment]
So good. Much thanks @nil0bject 

https://www.youtube.com/watch?v=12tce-THLUE&t=54s
