### ISSUE TITLE
Sandi Metz's Norms

### ISSUE THREAD

**Issue by ridget** [BrisRuby/meetups#91]
Sandi Metz is the author of practical object-oriented design in Ruby (hereforth referred to as POODR, because everyone else does, and I really don't want to have to type it again).  In the book she re-introduces aspects of object-oriented design as it applies to the language, and later suggested some rules for developers to follow when working with their Rails applications.

In this talk we'll be looking at those rules, how to apply them in a Rails environment, when to break them, and why you should care in the first place.

**Comment by patrickgordon** [comment]
Nice! I'll check out the book too.

**Comment by NicholasTD07** [comment]
+1

**Comment by ridget** [comment]
Will put slides up soon, but as promised heres a few links:

1. [RailsConf 2015 Vids](https://gist.github.com/seapy/8bc4e8a667578de8dffb)
2. [Refactoring, from good to great by Ben Orenstein](https://www.google.com.au/search?client=safari&rls=en&q=refactoring+from+good+to+great&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=NO8_VaLlK7Du8wft0YHQBQ)
3. [Rules, by Sandi Metz](https://www.youtube.com/watch?v=npOGOmkxuio)

I highly recommend you check out the [POODR book](http://www.poodr.com) if you haven't yet as well.

**Comment by elliotthilaire** [comment]
I bought the POODR book and I am a couple of chapters off finishing it.  I really don't like having books sit around not being used. Please, if you would like to read it let me know.

**Comment by davekinkead** [comment]
Love to have a browse when you are finished @elliotthilaire
