### ISSUE TITLE
Recommend books?

### ISSUE THREAD

**Issue by patrickgordon** [BrisRuby/meetups#92]
Hey all,

We were chatting at the dinner about some books for learning Ruby / RoR and now I'm keen to dive in to a couple.

Can we get a list of recommendations going here?

Include the title, author, the exp level its aimed at, and your brief thoughts on what you think about it.

Cheers!
Patrick

**Comment by ridget** [comment]
[Eloquent Ruby](http://eloquentruby.com) - Russ Olsen - Beginner/Intermediate - Excellent break down on some facets of the Ruby language, i.e. symbols, procs etc. Books very easy to read. 

[Practical Object Oriented Design in Ruby](http://poodr.com)  - Sandi Metz - All skill levels - Fantastic book, not overly long, but covers a lot of ground SRP, composition, inheritance, refactoring, testing techniques.

[Rails anti-patterns](http://railsantipatterns.com) - Chad Pytel and Tammer Saleh - Intermediate - Little old, but still very relevant techniques to refactor and improve your rails application.

[Design patterns in Ruby](http://designpatternsinruby.com) - Russ Olsen - Intermediate - Good translation of the Gang of Four design patterns into Ruby, need to finish reading this one, but really enjoyable. 

[Fearless Refactoring, Rails Controllers](http://rails-refactoring.com) - Andrzej Krzywda - Intermediate/Advanced -Bit of a shout out to this one, only picked it up last night, but really enjoying it so far, and there's a stupid amount of content in it. Really its about more than controllers. At $49 it's not cheap though.

[Ruby Science](https://gumroad.com/l/ruby-science) - Joe Ferris and Hallow Ward - Intermediate/Advanced - Honestly at $49 its a little expensive, but its worth a read.

Honestly, my top 3 picks would be (outside of the pickaxe book):

* Eloquent Ruby
* POODR
* Design Patterns In Ruby

I suspect the fearless refactoring will end up in there in place of one of the others though.

@michael-harrison suggested we do an open book review each month, and I know @DylanLacey was thinking along similar lines a while back.

**Comment by NicholasTD07** [comment]
@ridget Thanks for the list! Added to my reading list. :)

**Comment by hackling** [comment]
With regards to rails, I found [Agile Web Development in Ruby on Rails](https://pragprog.com/book/rails4/agile-web-development-with-rails-4) invaluable. It just covers all the basics, and you can run through it at whatever pace you are comfortable with.

**Comment by elliotthilaire** [comment]
This has been on my mind of a while. There are so many books to read and I can't decide which order to read them in.
 +1 for a quick book review segment at meetups.

**Comment by patrickgordon** [comment]
Decided to give Eloquent Ruby a run first. Was enjoying it until I fell
asleep :^). Will pick it up again tonight for sure.

**Comment by davekinkead** [comment]
All righty then, who is up for doing a 5-10 min review of a single book next month? I thought 2-3 people doing one book each might be a good format.

@patrickgordon - Eloquent Ruby?
@hackling - Agile rails?

Other takers?

**Comment by patrickgordon** [comment]
Sure, happy to do it!

**Comment by ridget** [comment]
For another great resource if youre learning Rails check out http://tutorials.jumpstartlab.com/ pretty much a full on curriculum.

**Comment by ghiculescu** [comment]
+1 would be keen to see this.

**Comment by davekinkead** [comment]
Okeydokey... 

I'd like to have this happening this month.  If you are keen, please add your name & book below. Format would be 5-10mins including target audience, a general overview, what you liked, what you didn't. Doesn't need to be ruby per se, so feel free to include git, general CS etc

@patrickgordon - Eloquent Ruby
@hackling  - Agile Web Development with Rails
....

@ridget @ghiculescu @nigelr @jasoncodes @jamesottaway @michael-harrison any other takers here?

**Comment by ghiculescu** [comment]
It's not related to ruby at all... but I read Masters of Doom - http://en.m.wikipedia.org/wiki/Masters_of_Doom - pretty recently and it was awesome. Happy to chat about it.

(Though I can't come this Tuesday because it's the gf's birthday and I want to be allowed to go to future ones.)

**Comment by elliotthilaire** [comment]
Since I have had trouble sourcing most of the above mentioned books from libraries, I have been thinking of purchasing a few and then trying to share them out as much as possible, once I have finished reading them.
 
1. Does anyone already own any of the previously mentioned books they would be willing to share?

2. Would anyone like to split an order? Probably from Amazon.

**Comment by ridget** [comment]
Closing this thread. Although it's super useful, I'm gonna try and keep our issues a bit tidier. Thanks all for the great discussion.
