### ISSUE TITLE
I'm stuck, anyone able to help?

### ISSUE THREAD

**Issue by patrickgordon** [BrisRuby/meetups#93]
Hey all

I don't know if there's a email list, facebook group, or anything similar so I've resorted to putting an issue here... Sorry in advance if its not the right place :^)

I was wondering if anyone was able to give me a hand with some issues I'm having with stripe, rails, and rspec? 

I've got a Q on stackoverflow open which explains what I'm trying to do:
http://stackoverflow.com/questions/28953426/how-do-i-test-stripe-and-my-controller-effectively

Cheers all

**Comment by ridget** [comment]
@patrickgordon I've put my response in there, happy to discuss further.

**Comment by ridget** [comment]
@patrickgordon you can reach me at tom.j.ridge on Skype or tom.ridge@tworedkites.com

**Comment by patrickgordon** [comment]
Legend. Thanks @ridget. I'll get in contact tonight.

**Comment by hackling** [comment]
It seems like there's a wealth of information on that SO answer, but for what it's worth, I used stripe-mock for my integration tests.

**Comment by patrickgordon** [comment]
Definitely a valuable discussion! Tom and I remote paired last night and
smashed out moving to a service object. I will refactor my tests tonight
too. I'm very new to testing so it is taking me much longer than I'd like
but I'm starting to see the benefits for sure.

**Comment by ridget** [comment]
closing this issue.
