### ISSUE TITLE
Suggestion: gitter chat

### ISSUE THREAD

**Issue by ridget** [BrisRuby/meetups#94]
Re latest issues on the repo, should we have these on the mailing list via the meetup or maybe we could look at setting up https://gitter.im for brisruby related chatter?

**Comment by patrickgordon** [comment]
I really like gitter.  +1 for that

**Comment by NicholasTD07** [comment]
I have been thinking of creating a Slack team/organization for BrisRuby. How do you like it?

**Comment by ghiculescu** [comment]
Great idea.

**Comment by jamesottaway** [comment]
:+1: for a Slack team!

**Comment by JaapRood** [comment]
We got the brisbane.slack.com team going, with a jelly channel, a js channel (although not properly populated yet), among some others too. If you think that's a good idea to keep all the Brisbane tech stuff under a team (we found with Jelly we just need a channel, not a whole other team), let me know. I can make whoever you'd like Admin who can invite everyone.

**Comment by ghiculescu** [comment]
Awesome. Can I get an invite? alex@tanda.co

**Comment by patrickgordon** [comment]
@JaapRood can I cop an invite? patrick [at] fitquick [dot] co

**Comment by JaapRood** [comment]
@ghiculescu @patrickgordon sent!

**Comment by patrickgordon** [comment]
Thanks mate!

**Comment by NicholasTD07** [comment]
I'd prefer a dedicated BrisRuby team. I like things properly organized and separated, like how classes should have a Single Responsibility.
One of the benefits of this dedicated BrisRuby team would be that we can have other channels to discuss other things, for example, great places to go or eat, while everyone know almost everyone else.

**Comment by JaapRood** [comment]
@NicholasTD07 if you just equate a Channel with a Class (instead of a team) you get the same thing ;) You can also create private groups if you want to discuss something with a select few. We have yet to really find a need for them, channels tend to be big enough to talk about anything really, but it's certainly something you can do.

I think there's quite a bit of cross over between all the Brissy meetups in people too and personally enjoy getting to know others as well. But in the end you'll have to decide for yourself as a meetup what to do. Just know there's a place for you guys at the Brisbane team :+1:

**Comment by ridget** [comment]
@nigelr @davekinkead you guys want to weigh in on this.

**Comment by NicholasTD07** [comment]
@ridget Or maybe we could have a poll at next meetup?

**Comment by zorfling** [comment]
@JaapRood can I get an invite too? zorfling@gmail.com
Cheers.

**Comment by JaapRood** [comment]
@zorfling sent!

**Comment by davekinkead** [comment]
I'll probably only ever log into one team. 

I hate to agree with Jaap but when he's right he's right. Channels seem like they are sufficient. 

--

Dave Kinkead
+61 431 946 160

**Comment by ridget** [comment]
@davekinkead cheers. @JaapRood can you flick me an invite too please.

**Comment by JaapRood** [comment]
@ridget done!

**Comment by danieldraper** [comment]
@JaapRood can you send me an invite too please hello@danieldraper.com.au

**Comment by JaapRood** [comment]
@danieldraper all set! I made @davekinkead an admin as well so he can send invitations as well (but please keep them coming, I'll be here all day :smile: ). If anyone else needs to be admin let him or me know.

**Comment by felixclack** [comment]
@JaapRood I'm new here, but would love an invite too. felixclack@gmail.com please.

**Comment by colinrc** [comment]
@JaapRood I'm only semi-regular but could you invite me too....    colin AT colincanfield.me

Thanks!

**Comment by JaapRood** [comment]
@felixclack @colinrc your invite is in the mail

**Comment by davekinkead** [comment]
Looks like everyone has migrated to the brisbane slack channels. Ping @JaapRood or myself for an invite...

**Comment by hjc1983** [comment]
@JaapRood @davekinkead,  can I get an invite too? hjc1983@gmail.com
Cheers.
