### ISSUE TITLE
Customising GitLab as a basis for modhub.io

### ISSUE THREAD

**Issue by tomjrob** [BrisRuby/meetups#96]
Hi all,

It has been suggested to me (thanks @ghiculescu) that people here might be interested in a talk on how we customised (are are continuing to customise) the GitLab open source project to form the basis for [modhub.io](http://modhub.io) (my brisbane based start-up).

#### What is ModHub?
The idea behind ModHub is basically to bring distributed software engineering workflow (inspired by git) to engineers (and financial modellers) who use spreadsheets. Currently, we've developed an excel add-in using c# which integrates with our web platform (the custom GitLab - built in RoR) and abstracts away the git commands.

#### What would I talk about?
As I've never done this before or attended the meetup, I guess I'd welcome some guidance. Firstly though, would people here be interested in a talk about this?

**Comment by ridget** [comment]
:+1: would be heaps keen to hear about this.

**Comment by ghiculescu** [comment]
I'm obviously keen.

**Comment by davekinkead** [comment]
Sounds cool

**Comment by elliotthilaire** [comment]
Looking forward to it.

**Comment by patrickgordon** [comment]
Great! Always keen to hear about more Brisbane start-ups.

**Comment by davekinkead** [comment]
Sounds like an interesting talk @tomjrob. Can you do it this month (Tues 24th)?

**Comment by tomjrob** [comment]
I sure can. How long do you normally want the talks to run for? And what kind of content is expected?

**Comment by davekinkead** [comment]
Sweet. You have about 20-30 mins to talk followed by Q&A.  

As to content...what problem were you trying to solve & how did you solve it (or didn't).  Tech or ruby content is a must but feel free to cover anything else you think is interesting like business/customer challenges.

**Comment by davekinkead** [comment]
All good for tomorrow @tomjrob?

**Comment by tomjrob** [comment]
Yep, yep. Should be fine. Will I need a slide deck, or is the go to just talk more conversationally?

**Comment by davekinkead** [comment]
Conversation is fine but a deck would be great - even if it's a readme in markdown we can turn it into some like this http://brisruby.org/intercom/

**Comment by nigelr** [comment]
thanks for the talk @tomjrob
