### ISSUE TITLE
Lightning Talk: rspec-the

### ISSUE THREAD

**Issue by jamesottaway** [BrisRuby/meetups#97]
I made a tiny gem to add some functionality to RSpec: https://github.com/jamesottaway/rspec-the

**Comment by hackling** [comment]
While we are doing talks on rspec-related gems, I'd be happy to give a quick demo of https://github.com/hackling/run_it_back

**Comment by ridget** [comment]
:+1: and :+1:

**Comment by davekinkead** [comment]
Perhaps we could have some kind of treasure trove of a shiny gem spectacular this month - a 5 minute tour of various gems that everyone has made recently....

**Comment by jamesottaway** [comment]
Did this last night. Let me know if anyone has more questions about `RSpec::The`.
