### ISSUE TITLE
RubyWars with BattleBots

### ISSUE THREAD

**Issue by davekinkead** [BrisRuby/meetups#98]
The repo is now up https://github.com/davekinkead/battlebots so fork it and make sure you watch it for any updates to the game rules that I arbitrarily decide to add.

If anything isn't clear, just add a comment on this issue and I'll respond and update the readme.

https://github.com/jlnr/gosu/ has all the instructions for the gem and dependencies. Everything is straight forward assuming you are on OSX.

When you are happy with your bot, add a pull request with it and we can battle it out.  I'll be accepting pull requests up until the meetup Tuesday so the more cunning of you might want to hold some secret logic in reserve.

Happy hunting!

**Comment by davekinkead** [comment]
Okey dokey.

The public API should now be stable....maybe.  But it's time start building and testing your bots :)

https://github.com/davekinkead/battlebots

**Comment by davekinkead** [comment]
I've just made Michael Bay very happy and added lots of explosions....so start building your bots!

**Comment by nigelr** [comment]
@davekinkead great work on preparing this and congrats to @elliotthilaire for winning...
